export default [
    {
        id: "1",
        nickName: "Rick",
        profileName: "@rickandmorty",
        timePosted: "10s",
        tweetText: "Paz entre os mundos!",
    },
    {
        id: "2",
        nickName: "mamãe do rato",
        profileName: "@egirldepreso",
        timePosted: "3min",
        tweetText: "Eu fiquei em choque que tem gente que assiste Rick amd Morty sem ser no meme!",
    },
    {
        id: "3",
        nickName: "Babi",
        profileName: "@bfpoletto",
        timePosted: "2d",
        tweetText: "Amanhã tem rick and morty e nada mais importa",
    },
    {
        id: "4",
        nickName: "m a n u",
        profileName: "@manu_mc1r",
        timePosted: "2d",
        tweetText: "E vamos de maratonar Rick and Morty de novo e de novo (melhor série, quem concorda respira)",
    },
    {
        id: "5",
        nickName: "Osses",
        profileName: "@Rafa_Osses",
        timePosted: "3d",
        tweetText: "Aeeeeee Caralho Rick and Morty dia 3 de maio",
    },
    {
        id: "6",
        nickName: "sadness",
        profileName: "@ana_chwan",
        timePosted: "2h",
        tweetText: "Não mereço sofrer sem álccol, vou voltar pro meu Rick and Morty",
    },
    {
        id: "7",
        nickName: "maya",
        profileName: "@mayamalheiros",
        timePosted: "22h",
        tweetText: "Rick and Morty é tudo pra mim",
    },
    {
        id: "8",
        nickName: "Kennedy Ribeiro",
        profileName: "@kennedy_rib1",
        timePosted: "1h",
        tweetText: "Rick and Morty n é pra ser engraçado e pra fazer vc duvidar da sua vidinha de merda talvez ser sua pior versão de todo o cosmos KKK",
    },
    {
        id: "9",
        nickName: "Nerd Bunker",
        profileName: "@Nerdbunker",
        timePosted: "1d",
        tweetText: "Homem-Formiga 3 contrada roteirista de Rick and Morty mla.bs/15933255",
    },
]